from setuptools import setup

setup (
    name='SmartMirror',
    version='1.0',
    packages=['venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip', 'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip.req',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip.vcs',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip.utils',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip.compat',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip.models',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.distlib',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.distlib._backport',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.colorama',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib._trie',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.filters',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treewalkers',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treeadapters',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.html5lib.treebuilders',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.lockfile',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.progress',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.chardet',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.util',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.contrib',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.packages',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.packaging',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.cachecontrol',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.cachecontrol.caches',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.webencodings',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip._vendor.pkg_resources',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip.commands',
              'venv.Lib.site-packages.pip-9.0.1-py3.5.egg.pip.operations'],
    url='',
    license='',
    author='not4juu',
    author_email='',
    description=''
)
